//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web.Mvc;
namespace Students_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_student
    {
        public int Student_key { get; set; }
        public string Student_name { get; set; }
        public int Subject_key { get; set; }
        public int grade { get; set; }
        public string Remarks { get; set; }
    
        public virtual mst_subject mst_subject { get; set; }
    }
    
}
